//json_file_format
var quiz = [

    {
        q: `Clinically, the transumbilical plane is an imaginary line passing through the umbilicus and which of the following vertebral levels?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->L2`,
        `<!--B. -->Intervertebral disc between L2 and L3`,
        `<!--C. -->L3`,
        `<!--D. -->Intervertebral disc between L3 and L4`,
        `<!--E. -->L4`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_1.xhtml#s0015">card 4-1</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following actions occurs with bilateral contraction of the external abdominal oblique muscle?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Compression of the abdominal contents`,
        `<!--B. -->Elevation of the rib cage`,
        `<!--C. -->Extension of the vertebral column`,
        `<!--D. -->Flexion of the thigh at the hip joint`,
        `<!--E. -->Rotation of the trunk`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9002">card 4-2</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `In the inguinal region, the aponeuroses of the internal abdominal oblique and transverse abdominal muscle fuse to form which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Conjoint tendon`,
        `<!--B. -->Inguinal ligament`,
        `<!--C. -->Lacunar ligament`,
        `<!--D. -->Linea alba`,
        `<!--E. -->Rectus sheath`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9003">card 4-3</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `How can the rectus abdominis muscle assist with respiration?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->It augments the action of the diaphragm on inspiration`,
        `<!--B. -->It depresses the rib cage on expiration`,
        `<!--C. -->It expands the lower rib cage on inspiration`,
        `<!--D. -->It flexes the trunk to assist with inspiration`,
        `<!--E. -->It tenses the anterior trunk on expiration`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9004">card 4-4</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following layers of the spermatic cord is derived from the internal abdominal oblique muscle?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Cremasteric fascia (muscle)`,
        `<!--B. -->External spermatic fascia`,
        `<!--C. -->Intercrural fibers`,
        `<!--D. -->Internal spermatic fascia`,
        `<!--E. -->Transversalis fascia`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A 38-year old man presents with an inguinal hernia. It is diagnosed as a direct inguinal hernia by which of the following criteria?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Enters the scrotum`,
        `<!--B. -->Passes lateral to the inferior epigastric vessels`,
        `<!--C. -->Passes through the deep inguinal ring`,
        `<!--D. -->Passes through the inguinal canal`,
        `<!--E. -->Passes through the inguinal triangle`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9005">card 4-5</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following layers of the rectus sheath form its posterior wall below the level of the arcuate line?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Aponeurosis of the internal abdominal oblique`,
        `<!--B. -->Aponeurosis of the transversusabdominis muscle`,
        `<!--C. -->Cremasteric fascia`,
        `<!--D. -->Peritoneum`,
        `<!--E. -->Transversalis fascia`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s0170">card 4-6</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A herniation of abdominal contents into the thorax may occur through which of the following regions?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Deep inguinal ring`,
        `<!--B. -->Lumbocostal triangle`,
        `<!--C. -->Rectus sheath`,
        `<!--D. -->Superficial inguinal ring`,
        `<!--E. -->Umbilicus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9007">card 4-7</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `An inflamed gallbladder that presses against the diaphragm may refer pain to the right lower neck and shoulder region. Sensory nerve fibers in which of the following nerves are responsible for this referred pain?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Greater splanchnic`,
        `<!--B. -->Long thoracic`,
        `<!--C. -->Phrenic`,
        `<!--D. -->Subcostal`,
        `<!--E. -->Vagus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_004_2.xhtml#s9008">card 4-8</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Bowel dysfunction associated with the parasympathetic innervation of the proximal gastrointestinal tract would most likely involve which of the following nerves?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Lumbar splanchnics`,
        `<!--B. -->Pelvic splanchnics`,
        `<!--C. -->Sacral splanchnics`,
        `<!--D. -->Thoracic splanchnics`,
        `<!--E. -->Vagus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0260">card 4-9</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The nerve cell bodies of pain afferents from an inflamed small intestine would mostly likely be located in which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anterior root`,
        `<!--B. -->Superior mesenteric ganglion`,
        `<!--C. -->Sympathetic trunk`,
        `<!--D. -->T10 dorsal root ganglion`,
        `<!--E. -->White ramus communicans`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0275">card 4-10</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Parasympathetic innervation to the urinary bladder arises from which of the following neural structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Inferior hypogastric plexus`,
        `<!--B. -->Inferior mesenteric ganglion`,
        `<!--C. -->Pelvic splanchnic nerves`,
        `<!--D. -->Superior hypogastric plexus`,
        `<!--E. -->Vagus nerves`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0290">card 4-11</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following abdominopelvic structures is most likely to refer pain to the epigastric region of the anterior abdominal wall?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Gallbladder`,
        `<!--B. -->Head of the pancreas`,
        `<!--C. -->Sigmoid colon`,
        `<!--D. -->Small intestine`,
        `<!--E. -->Spleen`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `After a meal rich in french fries, a 46-year-old woman begins to feel pain over the right shoulder that extends over the right suprascapular region. Which of the following organs is probably responsible for this episodic pain?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Duodenum`,
        `<!--B. -->Gallbladder`,
        `<!--C. -->Liver`,
        `<!--D. -->Pancreas`,
        `<!--E. -->Stomach`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_3.xhtml#s0305">card 4-12</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Venous blood draining from the inguinal region would most likely reach the internal thoracic veins by coursing through which of the following veins?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anterior intercostal`,
        `<!--B. -->Inferior and superior epigastric`,
        `<!--C. -->Superficial epigastric`,
        `<!--D. -->Superficial epigastric and lateral thoracic`,
        `<!--E. -->Thoracoepigastric`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0325">card 4-13</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following features is diagnostic of an indirect inguinal hernia?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->A hernia that is separate from the spermatic cord`,
        `<!--B. -->A hernia that lies outside the external spermatic fascia`,
        `<!--C. -->A hernia that occurs in Hesselbach’s (inguinal) triangle`,
        `<!--D. -->A hernia that passes lateral to the inferior epigastric vessels`,
        `<!--E. -->A hernia that passes only through the external inguinal ring`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0340">card 4-14</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following branches of the celiac trunk could be temporally clamped to stop bleeding from the cystic artery?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Gastroduodenal`,
        `<!--B. -->Left gastric`,
        `<!--C. -->Hepatic artery proper`,
        `<!--D. -->Right gastric`,
        `<!--E. -->Splenic`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0355">card 4-15</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following arteries is the major blood supply to the descending colon?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ileocolic`,
        `<!--B. -->Inferior mesenteric`,
        `<!--C. -->Marginal`,
        `<!--D. -->Middle colic`,
        `<!--E. -->Right colic`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0370">card 4-16</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The aorta enters the abdominal cavity by piercing the diaphragm at which of the following vertebral levels?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->T6`,
        `<!--B. -->T8`,
        `<!--C. -->T10`,
        `<!--D. -->T12`,
        `<!--E. -->L2`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A patient is diagnosed with an abdominal aortic aneurysm. Which of the following is the most likely location of this aneurysm?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Adjacent to the inferior mesenteric artery`,
        `<!--B. -->At the level of the renal arteries`,
        `<!--C. -->Just inferior to the celiac trunk`,
        `<!--D. -->Just superior to the superior mesenteric artery`,
        `<!--E. -->Where the aorta pierces the diaphragm`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0385">card 4-17</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following arteries lies just inferior to the origin of the renal arteries?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Gonadal`,
        `<!--B. -->Inferior mesenteric`,
        `<!--C. -->Median sacral`,
        `<!--D. -->Superior mesenteric`,
        `<!--E. -->Suprarenal`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0400">card 4-18</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following veins usually does <i>not</i> drain directly into the inferior vena cava?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Left common iliac`,
        `<!--B. -->Left gonadal`,
        `<!--C. -->Lumbar`,
        `<!--D. -->Right inferior phrenic`,
        `<!--E. -->Right renal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0415">card 4-19</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `If venous blood flow to the liver is obstructed, blood can return to the heart via the azygos vein, which has connections with which of the following veins?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Esophageal veins`,
        `<!--B. -->Paraumbilical veins`,
        `<!--C. -->Splenic vein`,
        `<!--D. -->Superior mesenteric vein`,
        `<!--E. -->Superior rectal vein`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_4.xhtml#s0430">card 4-20</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The greater omentum is tethered to the greater curvature of the stomach and also has a normal attachment to which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Duodenum`,
        `<!--B. -->Ileum`,
        `<!--C. -->Jejunum`,
        `<!--D. -->Spleen`,
        `<!--E. -->Transverse colon`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0450">card 4-21</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `If a surgeon passes his index finger through the epiploic foramen (of Winslow) and clamps down with his thumb, which of the following vessels would be obstructed?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Gastroduodenal artery`,
        `<!--B. -->Left gastric artery`,
        `<!--C. -->Hepatic artery proper`,
        `<!--D. -->Right gastroepiploic artery`,
        `<!--E. -->Superior mesenteric vein`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0465">card 4-22</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A perforated ulcer on the posterior wall of the stomach leaks gastric contents into the omental bursa (lesser sac) and would most likely endanger which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Common bile duct`,
        `<!--B. -->Esophagus`,
        `<!--C. -->Pancreas`,
        `<!--D. -->Right gastroepiploic artery`,
        `<!--E. -->Spleen`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0480">card 4-23</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A gallstone passes from the gallbladder into the cystic duct and down the common bile duct, where it becomes lodged. Which of the following is the most likely site of obstruction?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Hepatopancreatic ampulla`,
        `<!--B. -->Left hepatic duct`,
        `<!--C. -->Main pancreatic duct`,
        `<!--D. -->Spiral fold of the cystic duct`,
        `<!--E. -->Within the duodenum`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0495">card 4-24</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `In the fetus, blood from the placenta bypasses the liver by flowing through which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Azygos vein`,
        `<!--B. -->Ductus venosus`,
        `<!--C. -->Inferior vena cava`,
        `<!--D. -->Portal vein`,
        `<!--E. -->Umbilical vein`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0510">card 4-25</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `During surgery, which of the following features of the mesenteric small intestine would assist in identifying the jejunum?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Attaches to the cecum`,
        `<!--B. -->Has a larger diameter`,
        `<!--C. -->Has more fat in the mesentery`,
        `<!--D. -->Has shorter, straight arteries`,
        `<!--E. -->Is the more distal segment of the intestine`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0525">card 4-26</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Pain associated with the sigmoid colon would most likely be felt in which of the following regions?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Epigastric`,
        `<!--B. -->Hypogastric`,
        `<!--C. -->Left hypochondriac`,
        `<!--D. -->Left lower quadrant`,
        `<!--E. -->Periumbilical`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0540">card 4-27</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A kidney stone that enters the ureter and begins to descend toward the urinary bladder will most likely become lodged next in which of the following areas?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->As it crosses the iliac vessels`,
        `<!--B. -->Major calyx`,
        `<!--C. -->Renal papilla`,
        `<!--D. -->Uteropelvic junction`,
        `<!--E. -->Uterovesical junction`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0555">card 4-28</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following names is used to refer to the peritoneum that lines the inner aspect of the lower anterior abdominal wall?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Cardinal ligament`,
        `<!--B. -->Falciform ligament`,
        `<!--C. -->Greater omentum`,
        `<!--D. -->Parietal`,
        `<!--E. -->Transverse mesocolon`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0570">card 4-29</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures is <i>not</i> retroperitoneal?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Adrenal (suprarenal) gland`,
        `<!--B. -->Aorta`,
        `<!--C. -->Ascending colon`,
        `<!--D. -->Inferior vena cava`,
        `<!--E. -->Spleen`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0585">card 4-30</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Abdominal surgery results in a postoperative abdominal adhesion between the greater omentum and the anterior aspect of the ascending colon. Which of the following peritoneal layers is involved in this adhesion with the omentum?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Falciform ligament`,
        `<!--B. -->Hepatoduodenal ligament`,
        `<!--C. -->Lesser omentum`,
        `<!--D. -->Transverse mesocolon`,
        `<!--E. -->Visceral`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_004_5.xhtml#s0600">card 4-31</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    }

];
