//json_file_format
var quiz = [

    {
        q: `Which of the following ligaments separates the greater sciatic foramen from the lesser sciatic foramen?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Iliolumbar`,
        `<!--B. -->Posterior sacro-iliac`,
        `<!--C. -->Sacrococcygeal`,
        `<!--D. -->Sacrospinous`,
        `<!--E. -->Sacrotuberous`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A forensic physician wishes to determine if a pelvis is that of an adult female or male victim. Which of the following pelvic features is commonly associated with the female pelvis?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Obturator foramen is round`,
        `<!--B. -->Pelvic inlet is heart shaped`,
        `<!--C. -->Pelvic outlet is small`,
        `<!--D. -->Sacrum is long and narrow`,
        `<!--E. -->Pelvic arch is wide`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_1.xhtml#s0015">card 5-1</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The pelvic diaphragm is an important support structure for the pelvic viscera and is formed by two muscles, the levatorani and which of the following muscles?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Coccygeus`,
        `<!--B. -->Piriformis`,
        `<!--C. -->Obturatorexternus`,
        `<!--D. -->Obturatorinternus`,
        `<!--E. -->Superficial transverse peroneus`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0035">card 5-2</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following passageways from the pelvis to the gluteal region transmits the gluteal vessels and nerves?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Femoral canal`,
        `<!--B. -->Greater sciatic foramen`,
        `<!--C. -->Obturator foramen`,
        `<!--D. -->Pelvic outlet`,
        `<!--E. -->Superficial inguinal ring`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0070">card 5-3</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following perineal structures can be significantly weakened by a tear resulting from a difficult vaginal delivery?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bulbospongiosus muscle`,
        `<!--B. -->Ischiocavernosus muscle`,
        `<!--C. -->Levatorani muscle`,
        `<!--D. -->Perineal body`,
        `<!--E. -->Sacrotuberous ligament`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0105">card 5-4</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures lubricates the vaginal opening during sexual arousal?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bulbourethral glands`,
        `<!--B. -->Cervical mucus glands`,
        `<!--C. -->Cooper’s glands`,
        `<!--D. -->Glans clitoris`,
        `<!--E. -->Greater vestibular glands`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0120">card 5-5</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `During childbirth, stretching of which of the following structures will most likely lead to urinary incontinence?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bulbospongiosus muscle`,
        `<!--B. -->Ischiocavernosus muscle`,
        `<!--C. -->Levatorani`,
        `<!--D. -->Sphincter urethrae muscle`,
        `<!--E. -->Superficial transverse perineal muscle`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0135">card 5-6</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following nerves innervates the bulbospongiosus muscle?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Femoral`,
        `<!--B. -->Ilioinguinal`,
        `<!--C. -->Obturator`,
        `<!--D. -->Pelvic splanchnics`,
        `<!--E. -->Pudendal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0170">card 5-7</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following muscles is innervated by sympathetic nerve fibers?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bulbospongiosus`,
        `<!--B. -->Internal urethral sphincter`,
        `<!--C. -->Ischiocavernosus`,
        `<!--D. -->Levatorani`,
        `<!--E. -->Superficial transverse peroneus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0185">card 5-8</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `During defecation, which of the following muscles is relaxed by the action of the pelvic splanchnic nerves?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Colonic smooth muscle`,
        `<!--B. -->External anal sphincter`,
        `<!--C. -->Internal anal sphincter`,
        `<!--D. -->Levatorani`,
        `<!--E. -->Piriformis`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_2.xhtml#s0220">card 5-9</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Pain afferents from the body of the uterus travel in which of the following nerves?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ilioinguinal`,
        `<!--B. -->Lumbar splanchnics`,
        `<!--C. -->Pelvic splanchnics`,
        `<!--D. -->Pudendal`,
        `<!--E. -->Superior hypogastric plexus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0255">card 5-10</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Local anesthesia to the female vestibule would be targeted toward which of the following nerves?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ilioinguinal`,
        `<!--B. -->Genitofemoral`,
        `<!--C. -->Obturator`,
        `<!--D. -->Pelvic splanchnics`,
        `<!--E. -->Pudendal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0270">card 5-11</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Nitric oxide mediates the engorgement of the male erectile tissues and is released by which of the following nerves innervating the blood vessels of these tissues?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Genitofemoral`,
        `<!--B. -->Ilioinguinal`,
        `<!--C. -->Pelvic splanchnics`,
        `<!--D. -->Pudendal`,
        `<!--E. -->Superior hypogastric plexus`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_3.xhtml#s0285">card 5-12</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following branches of the internal iliac artery passes through both the greater and lesser sciatic foramen?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Inferior gluteal`,
        `<!--B. -->Internal pudendal`,
        `<!--C. -->Obturator`,
        `<!--D. -->Superior vesical`,
        `<!--E. -->Uterine`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0305">card 5-13</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following lymph node collections is most likely to receive lymphatic drainage from the labia majora?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->External iliac nodes`,
        `<!--B. -->Internal iliac nodes`,
        `<!--C. -->Lumbar nodes`,
        `<!--D. -->Para-aortic nodes`,
        `<!--E. -->Superficial inguinal nodes`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0320">card 5-14</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `External hemorrhoids are most likely to involve which of the following veins?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Inferior rectal`,
        `<!--B. -->Internal pudendal`,
        `<!--C. -->Internal rectal plexus`,
        `<!--D. -->Medial rectal`,
        `<!--E. -->Pampiniform plexus`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0335">card 5-15</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A countercurrent cooling mechanism is characteristic of which of the following set of veins?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Internal pudendal`,
        `<!--B. -->Left testicular`,
        `<!--C. -->Pampiniform`,
        `<!--D. -->Portal`,
        `<!--E. -->Prostatic`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0350">card 5-16</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Traumatic rupture of the spongy urethra can result in the spread of blood and urine into the lower abdominal wall. Between which two layers of the abdominal wall would you expect to find this exudate?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Skin and Camper’s fatty layer`,
        `<!--B. -->Camper’s fatty layer and Scarpa’s membranous layer`,
        `<!--C. -->Scarpa’s membranous layer and the investing fascia of the external abdominal oblique`,
        `<!--D. -->Investing fascia of the external abdominal oblique and internal abdominal oblique`,
        `<!--E. -->Investing fascia of the internal abdominal oblique and transversusabdominis`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0365">card 5-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0365">card 5-17</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0365">card 5-17</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0365">card 5-17</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Ascites (excess fluid in the peritoneal cavity) can accumulate in the lowest point in the female pelvis, where it can be accessed and drained from the cavity. Which of the following is the lowest point in the female abdominopelvic cavity?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Deep inguinal ring`,
        `<!--B. -->Left paracolic gutter`,
        `<!--C. -->Lesser sac`,
        `<!--D. -->Rectouterine pouch`,
        `<!--E. -->Right paracolic gutter`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_4.xhtml#s0380">card 5-18</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `An abscess at the level of the recto-anal junction spreads anteriorly through the bowel wall and would next encounter which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Obturatorinternus muscle`,
        `<!--B. -->Prostate gland`,
        `<!--C. -->Seminal vesicle`,
        `<!--D. -->Ureter`,
        `<!--E. -->Urinary bladder`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0400">card 5-19</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A surgeon clamping the uterine arteries before uterine surgery must be especially cognizant of which of the following structures in this region?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Lumbosacral trunk`,
        `<!--B. -->Ovarian artery`,
        `<!--C. -->Pudendal nerve`,
        `<!--D. -->Rectal veins`,
        `<!--E. -->Ureter`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures, in addition to the pelvic diaphragm and broad ligament, provide the strongest support for the uterus?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Cardinal (transverse) ligaments`,
        `<!--B. -->Median umbilical ligament`,
        `<!--C. -->Obturatorinternus muscle`,
        `<!--D. -->Round ligament of the uterus`,
        `<!--E. -->Uterovaginal fascia`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0420">card 5-20</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures provides an attachment point for the bulbospongiosus and external anal sphincter muscles?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Coccyx`,
        `<!--B. -->Ischial tuberosity`,
        `<!--C. -->Perineal body`,
        `<!--D. -->Pubic symphysis`,
        `<!--E. -->Sacrotuberous ligament`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0440">card 5-21</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `During pelvic surgery, the surgeon must be cognizant of the pathway of the retroperitoneal ureters, which pass superficial to or over which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ascending colon`,
        `<!--B. -->Common iliac artery`,
        `<!--C. -->Ductus deferens`,
        `<!--D. -->Right testicular vein`,
        `<!--E. -->Testicular artery`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0455">card 5-22</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The portion of the male urethra that passes through the penis is known by which of the following terms?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bulbous urethra`,
        `<!--B. -->Cavernosus urethra`,
        `<!--C. -->Membranous urethra`,
        `<!--D. -->Prostatic urethra`,
        `<!--E. -->Spongy urethra`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0470">card 5-23</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Millions of sperm are produced each day in the testes but are still immature. Where do the sperm reach full maturation?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ductus deferens`,
        `<!--B. -->Efferent ductules`,
        `<!--C. -->Epididymis`,
        `<!--D. -->Testicular lobules`,
        `<!--E. -->Rete testis`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0500">card 5-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_005_5.xhtml#s0485">card 5-24</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_005_5.xhtml#s0500">card 5-26</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    }

];
