//json_file_format
var quiz = [

    {
        q: `Fractured ribs are a common injury. Which of the following ribs is <i>least</i> likely to be fractured?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->2nd`,
        `<!--B. -->5th`,
        `<!--C. -->6th`,
        `<!--D. -->10th`,
        `<!--E. -->11th`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_1.xhtml#s0015">card 3-1</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following ligaments is most likely to be torn if the head of a rib and its articulation with the vertebra are compromised?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anterior longitudinal`,
        `<!--B. -->Interarticular`,
        `<!--C. -->Intertransverse`,
        `<!--D. -->Posterior longitudinal`,
        `<!--E. -->Radiate`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_1.xhtml#s0030">card 3-2</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following muscles assists in elevating the ribs during deep inspiration?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Diaphragm`,
        `<!--B. -->External intercostal`,
        `<!--C. -->Pectoralis major`,
        `<!--D. -->Rectus abdominis`,
        `<!--E. -->Sternohyoid`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0050">card 3-3</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following muscles helps depress the ribs during expiration?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anterior scalene`,
        `<!--B. -->External intercostals`,
        `<!--C. -->Levator scapulae`,
        `<!--D. -->Lower internal intercostals`,
        `<!--E. -->Pectoralis minor`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0085">card 3-4</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following muscles lie deep (posterior) to the internal thoracic vessels?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->External intercostals`,
        `<!--B. -->Innermost intercostals`,
        `<!--C. -->Internal intercostals`,
        `<!--D. -->Scalenes`,
        `<!--E. -->Transversusthoracis`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0120">card 3-5</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Following surgery to the breast, the patient presented with a unilateral “winging” of the scapula. Which of the following nerves was most likely damaged?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Lateral pectoral`,
        `<!--B. -->Long thoracic`,
        `<!--C. -->Lower subscapular`,
        `<!--D. -->Suprascapular`,
        `<!--E. -->Thoracodorsal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0155">card 3-6</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A tumor in the left lung displaces the left main bronchus. Which of the following structures is most likely compressed by the displaced bronchus?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Aortic arch`,
        `<!--B. -->Azygos vein`,
        `<!--C. -->Esophagus`,
        `<!--D. -->Thoracic duct`,
        `<!--E. -->Thymus gland`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_003_2.xhtml#s0190">card 3-7</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `When introducing a needle into the thoracic cavity, why is the needle inserted superior to a rib rather than just inferior to the rib margin?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->To avoid piercing the inferior lobe of the lung`,
        `<!--B. -->To avoid piercing the intercostal neurovascular bundle`,
        `<!--C. -->To avoid piercing the internal thoracic artery`,
        `<!--D. -->To avoid piercing the parietal pleura`,
        `<!--E. -->To avoid piercing the transversusthoracis muscle`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0210">card 3-8</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The pain associated with myocardial ischemia (angina pectoris) most likely is conveyed along visceral afferent nerve fibers that enter which of the following spinal cord levels?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->C3-5`,
        `<!--B. -->T1-4`,
        `<!--C. -->T10-12`,
        `<!--D. -->L1-2`,
        `<!--E. -->L2-4`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0225">card 3-9</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following nerves form a plexus on the esophagus?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Greater splanchnic nerves`,
        `<!--B. -->Intercostal nerves`,
        `<!--C. -->Least splanchnic nerves`,
        `<!--D. -->Lesser splanchnic nerves`,
        `<!--E. -->Vagus nerves`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_3.xhtml#s0240">card 3-10</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Intercostal arteries form an important anastomosis with which of the following arteries?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Axillary`,
        `<!--B. -->Brachiocephalic`,
        `<!--C. -->Internal thoracic`,
        `<!--D. -->Subclavian`,
        `<!--E. -->Superior epigastric`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0260">card 3-11</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The collection of blood in the pericardial sac can compromise the force of contraction of the heart’s chambers and is termed cardiac _________:`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Infarct`,
        `<!--B. -->Insufficiency`,
        `<!--C. -->Ischemia`,
        `<!--D. -->Rebound`,
        `<!--E. -->Tamponade`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0275">card 3-12</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following coronary vessels usually supplies blood to most of the interventricular septum?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Circumflex`,
        `<!--B. -->Left anterior descending`,
        `<!--C. -->Left marginal`,
        `<!--D. -->Posterior descending`,
        `<!--E. -->Right marginal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0290">card 3-13</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following vessels is most often responsible for a myocardial infarction?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Circumflex`,
        `<!--B. -->Left anterior descending`,
        `<!--C. -->Posterior descending`,
        `<!--D. -->Right marginal`,
        `<!--E. -->SA nodal`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following arteries is the major blood supply to the lungs?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Bronchial`,
        `<!--B. -->Internal thoracic`,
        `<!--C. -->Mediastinal`,
        `<!--D. -->Pericardiacophrenic`,
        `<!--E. -->Pulmonary`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0305">card 3-14</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Although the azygos vein is important in portosystemic anastomoses, it normally drains into which of the following veins?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Hemiazygos`,
        `<!--B. -->Inferior vena cava`,
        `<!--C. -->Left gastric`,
        `<!--D. -->Right brachiocephalic`,
        `<!--E. -->Superior vena cava`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_4.xhtml#s0320">card 3-15</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following sets of lymph nodes is a major site of metastasis of cancer cells from the breast?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Axillary`,
        `<!--B. -->Infraclavicular`,
        `<!--C. -->Parasternal`,
        `<!--D. -->Pulmonary`,
        `<!--E. -->Supraclavicular`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#s0340">card 3-16</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Pleura lining the inner aspect of the anterior thoracic wall becomes inflamed and painful. Which of the following portions of the pleura is most likely involved in this inflammatory process?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Costal pleura`,
        `<!--B. -->Diaphragmatic pleura`,
        `<!--C. -->Mediastinal pleura`,
        `<!--D. -->Pulmonary ligament`,
        `<!--E. -->Visceral`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0360">card 3-18</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `A surgeon wishes to clamp the pulmonary artery at the hilum of the right lung. Where would she look for this artery?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anteroinferiorly`,
        `<!--B. -->Inferiorly`,
        `<!--C. -->Posteriorly`,
        `<!--D. -->Posteroinferiorly`,
        `<!--E. -->Superiorly`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`,
        `<b><!--E. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 4,
        ansText: `<b><!--E. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0375">card 3-20</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `The parietal serous pericardium lines which of the following structures?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Epicardium`,
        `<!--B. -->Fibrous pericardium`,
        `<!--C. -->Mediastinal pleura`,
        `<!--D. -->Proximal aorta`,
        `<!--E. -->Proximal pulmonary trunk`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0390">card 3-21</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `If a surgeon’s finger is in the transverse pericardial sinus, what is the relationship of his finger to the superior vena cava?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Anterior`,
        `<!--B. -->Inferior`,
        `<!--C. -->Lateral`,
        `<!--D. -->Posterior`,
        `<!--E. -->Superior`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0405">card 3-22</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following features of the right atrium separates the pectinate muscle from the sinus venarum (smooth portion of the inner atrium wall)?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Crista terminalis`,
        `<!--B. -->Fossa ovalis`,
        `<!--C. -->Opening of the coronary sinus`,
        `<!--D. -->Right auricle`,
        `<!--E. -->Tricuspid valve`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0420">card 3-23</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Why might the right ventricle become hypertrophied in a heart with a ventricular septal defect?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Absence of the septomarginaltrabecula (moderator band)`,
        `<!--B. -->Increased blood volume from the left side`,
        `<!--C. -->Obstruction of the mitral valve`,
        `<!--D. -->Prolapse of the tricuspid valve`,
        `<!--E. -->Reduced right ventricular filling`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0435">card 3-24</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures is responsible for the 1st heart sound heard with a stethoscope?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Closure of the aortic and pulmonary valves`,
        `<!--B. -->Closure of the mitral and pulmonary valves`,
        `<!--C. -->Contraction of the right and left ventricles`,
        `<!--D. -->Prolapse of the bicuspid and tricuspid valves`,
        `<!--E. -->Relaxation of the left and right atria`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`,
        `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 1,
        ansText: `<b><!--B. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0450">card 3-25</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Why might ischemia to the interventricular septum disrupt the rhythmicity of the heart?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->It may affect the subendocardial conduction system`,
        `<!--B. -->It may block the AV node conduction`,
        `<!--C. -->It may block the SA node conduction`,
        `<!--D. -->It may decrease venous return`,
        `<!--E. -->It may inhibit the vagus nerve`],
        optionFeedback: [`<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 0,
        ansText: `<b><!--A. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0465">card 3-26</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Where is the best place to hear the closure of the mitral valve with your stethoscope?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Directly over the lower portion of the body of the sternum`,
        `<!--B. -->Left 2nd intercostal space lateral to the sternum`,
        `<!--C. -->Left 5th intercostal space at the midclavicular line`,
        `<!--D. -->Right 2nd intercostal space lateral to the sternum`,
        `<!--E. -->Right 5th intercostal space lateral to the sternum`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`,
        `<b><!--C. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 2,
        ansText: `<b><!--C. -->(See <a href="../../../xhtml/Section_003_5.xhtml#st0480">card 3-27</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    },

    {
        q: `Which of the following structures lies just posterior to the left atrium and can be compressed if the atrium is enlarged?`,
        q2: ``,
        q3: [],
        option: [`<!--A. -->Ascending aorta`,
        `<!--B. -->Azygos vein`,
        `<!--C. -->Descending aorta`,
        `<!--D. -->Esophagus`,
        `<!--E. -->Thoracic duct`],
        optionFeedback: [`<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`,
        `<b><!--D. -->(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`,
        `<b>(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`],
        optionStyleType: `st-upper-alpha`,
        answer: 3,
        ansText: `<b><!--D. -->(See <a href="../../../xhtml/Section_003_5.xhtml#s0490">card 3-28</a>)</b>`,
        state: `notAnswered`,
        userAnswered: ``
    }

];
